"""Level Factory 0.144.2: VERSION and the CHANGELOG entry for
`patch_lf_site_spec_at_dispatch.py`, written after the failing tests and the
suite were measured.

    python patch_lf_site_spec_at_dispatch_release.py
"""
import pathlib

LF = pathlib.Path(__file__).resolve().parent.parent / "level_factory"

ENTRY = '''## [0.144.2] - Lot's site spec is written again at dispatch, once what it measures exists

**Cold run 9171 (county_hospital_001, the breadth sweep) could not export:**

    export blocked by functional regression:
      - gameplay-anchor registry changed after art pass
      - interactive registry changed after art pass

**Measured on the run's own records.** The artifact index holds two versions
of the selected candidate's `site.site.gameplay.json`:

| | v1, shell leg | v2, after the lock |
|---|---|---|
| registered | 23:16:05 | 23:54:16 |
| declared plate | 100 x 108 m | 93 x 71 m |
| building b0 at | (-6, -10) | (-6, 0) |
| anchors and interactives | 43 and 26 | the same ids, all moved |

The `plan` step wrote the site specs at 23:15:37, and Deli Counter generated
the shell at 23:16:03. With no lot library, the building a site places is
generated by the Deli Counter job the assembly depends on.
- So at plan time `site_variation.shell_footprint` had nothing to read, and
  the plate and spacing fell back to `DEFAULT_FOOTPRINT` (48 x 48 m).
- `run --art` re-planned at 23:54:14, measured the 40 x 30 m shell, and
  wrote a different site.
- The selected candidate's assembly re-ran at 23:54:15, two seconds after
  the lock.
- The export refused it correctly: the site that would ship was not the site
  that was judged.

**Old, and newly caught.** The measurement dates from 27 July, and this
mission exported in September (cold run 9005), so the drift most likely
existed then, before the lock guarded site data. Library shells exist before
any plan, which is why no library mission has met it. Every brief without a
`lot_library` -- the default for a new brief -- would.

**The fix: a spec finished at dispatch.**
- **The scheduler** (`packages/jobs/scheduler.py`, `_attempt_job`). A job
  spec may carry `prepare(spec) -> spec`. It runs on the first attempt, when
  every dependency has succeeded, before anything reads the spec.
  - The returned spec carries no `prepare`, so a retry does not run it
    again.
  - One that raises, or returns a spec still carrying `prepare`, fails that
    job with `INPUT_VALIDATION_ERROR`, not the run.
- **Lot's spec builder** (`apps/cli/commands/__init__.py`). Every job whose
  spec `_write_site_spec` writes (the assemblies, greybox and themed) gets a
  `prepare` that writes it again from the same arguments, through
  `_site_spec_at_dispatch`.
  - It refuses if the spec would land at a different path from the one
    planned.
  - It returns the spec it was handed, so a batch's merged keys
    (`skins_dir`) survive.
- **Plan time is unchanged.** Its write stays, provisional where a job's
  inputs are not built yet.

**What it invalidates.** A no-library candidate now assembles on its
measured plate, not the default, so its site, and every evaluation of it,
differs from what an earlier run cached. On a library mission both writes
are the same bytes, and nothing changes.

**Tests** (`tests/unit/test_site_spec_at_dispatch.py`, 5, all failing on
0.144.1):
- `prepare` runs once, after the job it depends on has built, and the tool
  sees the spec it returned;
- a `prepare` that raises fails its job and not the run;
- the dispatch write uses the plan's arguments, keeps a batch's keys, and
  refuses a moved path;
- the lot branch of `_job_specs_for_plan` attaches it.

**Suite:** 1,929 collected: 1,914 passed, 14 skipped, 1 xfail. That is
0.144.1's 1,923, plus these 5, plus one `test_sibling_locator` case for the
new file.

**Unproven until it runs:** the cold re-run of county_hospital_001.

'''


def main():
    version = LF / "VERSION"
    changelog = LF / "CHANGELOG.md"
    v = version.read_bytes()
    assert v == b"0.144.1", v
    c = changelog.read_bytes()
    assert b"\r\n" not in c
    assert c.startswith(b"## [0.144.1] - "), c[:60]
    version.write_bytes(b"0.144.2")
    changelog.write_bytes(ENTRY.encode("utf-8") + c)
    print("Level Factory 0.144.2: VERSION and CHANGELOG")


if __name__ == "__main__":
    main()
