"""PIPELINE_ROADMAP.md after cold run 9185: close 187 (option A, proven),
add FLAPPAHS's colours to 186, put the blended far fabric and 9185 into 188,
and file 189 (a building's walkable connectivity depends on where it lands on
the voxel grid). Run `tools/roadmap_status.py --write` then `--check` after.

    python patch_roadmap_9185.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ROADMAP = ROOT / "PIPELINE_ROADMAP.md"

OLD_186 = "*STATUS: NARROWED 2026-10-06 -- the gas station and the convenience store are done and proven: Deli Counter 0.188.0, Zoo 1.75.0, Pixelcoat 0.58.0, Level Factory 0.146.0; cold runs 9181 (a never-seen one-building convenience store, generated) and 9182 (gas_block_001), both 0 interventions. The strip club's band no longer contradicts its neon (item 187's option D). Open: deli detail; the brief words still refused (`deli`, `night_deli`, `stop_n_go`, `corner_store`, `nightclub`).*"
NEW_186 = "*STATUS: NARROWED 2026-10-06 -- the gas station and the convenience store are done and proven: Deli Counter 0.188.0, Zoo 1.75.0, Pixelcoat 0.58.0, Level Factory 0.146.0; cold runs 9181 (a never-seen one-building convenience store, generated) and 9182 (gas_block_001), both 0 interventions. The strip club's band no longer contradicts its neon (item 187's option D). FLAPPAHS is cream on green on every sign, the walker's call: Pixelcoat 0.60.0 draws the band in Zoo's colourway 0. No cold run has drawn a FLAPPAHS store since. Open: deli detail; the brief words still refused (`deli`, `night_deli`, `stop_n_go`, `corner_store`, `nightclub`).*"

OLD_187 = "*STATUS: NARROWED 2026-10-06 -- option D shipped: Level Factory 0.147.0 (a band names a shop; 68 of 148 library shells are dealt one, where all 148 were) and Zoo 1.76.0 (a retail strip is not a strip club). Open: a named shop's band and door still say two different names -- option A (one table, Zoo's names on both) or B (the door says the band's name) is the walker's call.*"
NEW_187 = '*STATUS: CLOSED 2026-10-06 -- option A, the walker\'s call ("Agreed"): one name list on both signs, the door box\'s. Pixelcoat 0.61.0 holds it (each shop family holds exactly Zoo\'s door names, mirror-tested against Zoo\'s source); Level Factory 0.148.0 deals one business a shell and hands that pack to the shell\'s fixtures job; Zoo 1.79.0\'s door box wears it. Cold run 9185 (restaurant_row_001), 0 interventions: deli_a01\'s band and door box both say SCRAPPLE & SONS DELI (`M_SignBox_sign_scrapple_sons_deli_Face`, in the package); the office and the rail station take no band and show one name each.*'

OLD_188 = "*STATUS: OPEN 2026-10-06 -- phase one shipped: Zoo 1.77.0's `chain_link_fence` (two draws a run) and Lot 0.97.0's `site_fences`, closing an Empty row's gaps and ends; Pixelcoat 0.59.0 lists `chain_link` as a kind Zoo knows. Cold run 9183 is its first level: seven fences on gas_block_001, 0 interventions, findings 57 -> 57 against 9182 on the same candidate. Seen at 7 m, an alley reads as a gated alley. Seen along a 16.8 m run, the far fabric is cut away -- alpha-test mip thinning, the fabric being about 25 % wire -- and that is the next step (coverage-preserving mips, a lower cutoff for this kind, or a distant card; a look-and-price call). Priced against 9182 run twice: +3.8 draws a station, +0.020 ms median against a control spread of 0.124 ms -- under the floor; its +32 mesh instances included 22 from a plate that grew 4 m past each end fence (`site_extent.required_rect` counted fences as content), leaving a walk-around at both ends of the row -- fixed in Lot 0.97.1, re-assembled at 246 m. Open after that: the plate perimeter, which needs the backdrop behind it because the fence is see-through; vacant lots; Empties not in a row.*"
NEW_188 = "*STATUS: OPEN 2026-10-06 -- phase one shipped: Zoo 1.77.0's `chain_link_fence` (two draws a run) and Lot 0.97.0's `site_fences`, closing an Empty row's gaps and ends; Pixelcoat 0.59.0 lists `chain_link` as a kind Zoo knows. Cold run 9183 is its first level: seven fences on gas_block_001, 0 interventions, findings 57 -> 57 against 9182 on the same candidate. Priced against 9182 run twice: +3.8 draws a station, +0.020 ms median against a control spread of 0.124 ms -- under the floor; its +32 mesh instances included 22 from a plate that grew 4 m past each end fence, fixed in Lot 0.97.1 (cold run 9184, back to 246 m). THE FAR FABRIC, cut away by alpha-test mip thinning in 9183, is BLENDED since Zoo 1.78.0 and Pixelcoat 0.60.0. Rendered on 9184's walk copy, a 0.2 cutoff and alpha hash went solid dark, and the distant card the walker leaned to still left a long run bare seen along its length (a visibility range switches a whole node, and one run is one node); the blended texture keeps the near wire and leaves a faint far screen, with no extra draw. Cold run 9185 (restaurant_row_001), 0 interventions: six fences on the Empty row's front line, every fabric `BLEND`, both end runs stopping on the perimeter at x +-98. NOT YET PRICED in frame time against the alpha test: a run was started and stopped for a pause before any report (`docs/cold_runs/cold_9185/price_fabric.sh` reruns it); also to check in frames, the fence's shadow blended against alpha-tested. Open after that: the plate perimeter, which needs the backdrop behind it because the fence is see-through; vacant lots; Empties not in a row.*"

OLD_TAIL = '**WHY NOT THE PERIMETER FIRST.** The perimeter is four opaque 3 m boxes ("the edge of the world: bright, flat, dead"). Chain link is see-through, so a fence there shows the void beyond the plate until a backdrop stands behind it, which is the walker\'s next item after the Empties.\n'
NEW_TAIL = OLD_TAIL + '\n*STATUS: OPEN 2026-10-06 -- FOUND, NOT STARTED. Cold run 9185 lost two of its three candidates to it, and the third was clean (0 interventions). deli_a03\'s upper floor joins its ground floor at 8 of 32 voxel-grid origins (`docs/findings/stairwell_on_one_grid_in_four/`). Next: the library census written beside the finding (`grid_census.py`, not yet run), then the fix where the census says.*\n\n**189. A building\'s walkable connectivity depends on where it lands on the voxel grid.** Found 2026-10-06, closing cold run 9185 (`docs/findings/stairwell_on_one_grid_in_four/`).\n\n**WHAT WAS MEASURED.**\n- 9185 dropped seed_9003 and seed_9205 for `walktest not ok`. Both stand deli_a03, and in both the objective upstairs (`OBJECTIVE_A`) is off the navmesh\'s main network. In 9179 the same anchor was off it too, and passed.\n- **The verdict came from an engine error.** The walk test passes an unreachable anchor as "VERTICAL access" when Godot\'s fallback path ends under it. In 9185 that fallback hit Godot\'s internal "It\'s not expect to not find the most reachable polygons" on each failing call and returned a path that stopped near home; the same target from `proxy_1` still ended under the anchor and passed.\n- **The cause is a stairwell.** Baked alone, deli_a03\'s upper floor joins the ground floor at 8 of 32 grid origins, all at one X offset; the Y and Z offsets change nothing. The stairwell\'s only way in, the 1.25 m `office_stair_door`, opens into a neck pinched between two stair heads. Baked as a whole site, seed_9003 reproduces the walk test\'s 4,254 polygons and puts the stairwell, the stair and the whole upper floor on one island of 364, cut off from the street.\n- **The gate that should see it bakes once.** Deli Counter\'s nav gate passed deli_a03 at its own grid origin.\n\n**WHY IT MATTERS.** Which candidates survive the walk test is decided by the grid a building lands on and by whether an engine fallback succeeds. A brief that draws such a shell into every candidate could lose them all, which is an intervention. Bots in a level that ships with the stairwell unbaked cannot reach the objective.\n\n**REFUTED, KEPT.** That the site outgrew Godot\'s 4,096-polygon path-search cap: 9179\'s passing seed_9003 baked 5,251 polygons, and 9185\'s failing one 4,254.\n\n**OPEN, IN ORDER.**\n1. The census: every library shell at eight grid origins, every pair of floor markers and stair ends that is connected at some origins and not all.\n2. The source fix, by what the census shows: a door never opens where a stair head pinches its landing, and Deli Counter\'s gate requires connectivity at every origin.\n3. The walk test decides ladder access from geometry it can see, the same from any start, and says when the engine errored.\n'


def main():
    text = ROADMAP.read_bytes().decode("utf-8")
    assert "\r\n" not in text, "the roadmap is LF; CRLF here means it changed under us"
    for old, new in ((OLD_186, NEW_186), (OLD_187, NEW_187), (OLD_188, NEW_188)):
        n = text.count(old + "\n")
        assert n == 1, ("anchor matched %d times" % n, old[:80])
        text = text.replace(old + "\n", new + "\n")
    assert text.endswith(OLD_TAIL), "the roadmap no longer ends with item 188's last paragraph"
    text = text[:-len(OLD_TAIL)] + NEW_TAIL
    ROADMAP.write_bytes(text.encode("utf-8"))
    print("PIPELINE_ROADMAP.md: 186, 187, 188 statuses; item 189 filed")


if __name__ == "__main__":
    main()
