"""Level Factory 0.144.2: Lot's site spec is written again at dispatch, once
the job's dependencies have built what it measures.

Cold run 9171 (county_hospital_001, the breadth sweep) could not export:
"export blocked by functional regression: gameplay-anchor registry changed
after art pass; interactive registry changed after art pass". Measured:

  * the `plan` step wrote every candidate's site spec at 23:15:37; Deli
    Counter generated `shell.glb` at 23:16:03. With no library, the building
    a site places is generated by the Deli Counter job the assembly depends
    on, so `shell_footprint` had nothing to read and the plate and spacing
    fell back to `DEFAULT_FOOTPRINT` (48 x 48 m): 100 x 108 m, b0 at y -10.
  * `run --art` re-planned at 23:54:14, measured the 40 x 30 m shell, wrote
    93 x 71 m with b0 at y 0, and the selected candidate's assembly re-ran at
    23:54:15 -- the lock had been taken at 23:54:13. Every anchor moved.

The fix leaves plan time exactly as it was and adds one step: a job spec may
carry `prepare(spec) -> spec`, which the scheduler runs when the job is
dispatched, after its dependencies have succeeded; Lot's spec builder hands
it one that writes the site spec again from the same arguments.

    python patch_lf_site_spec_at_dispatch.py
"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
LF = ROOT / "level_factory"

SCHED_OLD = '''        # 0. Tactical advisories -- what the tool will build and grade badly,
'''
SCHED_NEW = '''        # BEFORE ANYTHING READS THE SPEC: a spec finished at dispatch
        # (0.144.2). A job spec may carry `prepare`, a callable given the spec
        # and returning the spec this job runs with. It runs here, on the
        # first attempt, when every dependency has succeeded -- because some
        # specs describe what their dependencies build. Lot's site spec
        # measures the building it places, and with no lot library the Deli
        # Counter job this one depends on generates that building: written at
        # plan time it was sized from a default, and the next plan, made after
        # the shell existed, wrote a different site (cold run 9171). The
        # returned spec carries no `prepare`, so a retry does not run it again.
        # One that raises fails this job, not the run.
        prepare = job_spec.get("prepare") if isinstance(job_spec, Mapping) else None
        if callable(prepare):
            try:
                job_spec = prepare(dict(job_spec))
            except Exception as exc:  # this job's failure, reported as one
                return self._fail(job, INPUT_VALIDATION_ERROR,
                                  f"the job spec could not be finished at dispatch: {exc}")
            if not isinstance(job_spec, Mapping) or "prepare" in job_spec:
                return self._fail(job, INPUT_VALIDATION_ERROR,
                                  "a spec's prepare step must return the finished "
                                  "spec, without prepare")

        # 0. Tactical advisories -- what the tool will build and grade badly,
'''

HELPER_ANCHOR = "def _write_site_spec(ws: Workspace, model: MissionBrief, deli_out: Path,\n"
HELPER_NEW = '''def _site_spec_at_dispatch(ws: Workspace, model: MissionBrief, deli_out: Path,
                           spec: dict, **kw) -> dict:
    """A Lot job's spec, finished when the scheduler dispatches the job
    (0.144.2): `_write_site_spec` again, now that the job's dependencies have
    run, and the spec handed back without its `prepare`.

    WHY AT DISPATCH. `_write_site_spec` measures the building it places
    (`site_variation.shell_footprint`). With no lot library that building is
    generated by the Deli Counter job the assembly depends on, so at plan time
    there was nothing to measure and the plate and spacing fell back to
    `DEFAULT_FOOTPRINT` (48 x 48 m). Every later plan, made after the shell
    existed, measured it and wrote a different site. Cold run 9171
    (county_hospital_001): the candidates were judged on a 100 x 108 m plate
    with b0 at y -10. `run --art` re-planned, measured the 40 x 30 m shell and
    re-assembled the selected candidate on 93 x 71 m with b0 at y 0, two
    seconds after the functional lock -- and the export refused it as a
    functional regression, correctly: it was not the site that was judged.

    The plan-time write stays. It is what anything that reads a spec before
    its job runs reads, provisional where the job's inputs are not built yet.
    Library shells exist before any plan, so on that path both writes are the
    same bytes.
    """
    written = _write_site_spec(ws, model, deli_out, **kw)
    if str(written) != str(spec.get("site_spec_path")):
        raise RuntimeError(f"the site spec moved between plan and dispatch: "
                           f"{spec.get('site_spec_path')} -> {written}")
    return {k: v for k, v in spec.items() if k != "prepare"}


def _write_site_spec(ws: Workspace, model: MissionBrief, deli_out: Path,
'''

LOT_OLD = '''                    else [str(_latest_output(deli_out, "shell.glb"))]),
            }
        elif job.adapter_id == "walktest":
'''
LOT_NEW = '''                    else [str(_latest_output(deli_out, "shell.glb"))]),
            }
            # Written again at dispatch, from the same arguments, once the
            # job's dependencies have built what it measures -- see
            # `_site_spec_at_dispatch` (0.144.2).
            from functools import partial
            specs[job.job_id]["prepare"] = partial(
                _site_spec_at_dispatch, ws, model, deli_out, seed=seed,
                themed_scene=themed_scene, ground_skins=ground_skins,
                cover_modules=cover_modules, pixelcoat_out=pixelcoat_out)
        elif job.adapter_id == "walktest":
'''

TEST = '''"""A job spec can be finished at dispatch, and Lot's site spec is (0.144.2).

COLD RUN 9171 (county_hospital_001, the breadth sweep) could not export. Its
site spec was written at plan time, before the Deli Counter job generated the
building it places, so `shell_footprint` had nothing to read and the plate and
spacing fell back to `DEFAULT_FOOTPRINT`: the candidates were judged on a
100 x 108 m plate. `run --art` re-planned after the shell existed, measured it
and wrote a 93 x 71 m site, the selected candidate re-assembled after the
functional lock, and the export refused the drift.

These pin both halves: the scheduler runs a spec's `prepare` at dispatch,
after the job's dependencies have succeeded, and Lot's spec builder hands it
one that writes the site spec again.

Run:  python -m pytest tests/unit/test_site_spec_at_dispatch.py -q
"""
import inspect
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from packages.adapters.registry import AdapterRegistry  # noqa: E402
from packages.adapters.sdk import BaseAdapter, PlannedCommand, ToolProbe  # noqa: E402
from packages.artifacts.cache import ContentCache  # noqa: E402
from packages.core import states  # noqa: E402
from packages.core.models import Job  # noqa: E402
from packages.jobs.scheduler import Scheduler  # noqa: E402
from packages.pipeline.graph import JobGraph  # noqa: E402
from packages.project_store.index import Index  # noqa: E402


class _Adapter(BaseAdapter):
    """Writes `shell.glb`, and records the spec each job was planned with."""

    adapter_id = "fake_prepare"
    adapter_version = "0.1.0"
    capabilities = frozenset({"x"})
    output_contract_version = "fake.0.1"

    def probe(self, installation):
        return ToolProbe(True, "0.1.0", None, {}, self.capabilities)

    def validate_configuration(self, job_spec, context):
        return []

    def plan_commands(self, job_spec, context):
        self.seen[job_spec.get("name")] = dict(job_spec)
        work = Path(str(context["work_dir"]))
        py = context.get("python_executable") or "python3"
        script = f"open({str(work / 'shell.glb')!r}, 'w').write('x')"
        return [PlannedCommand(
            executable=Path(str(py)), arguments=("-c", script),
            working_directory=work, expected_outputs=("shell.glb",),
            resource_class="lightweight", timeout_seconds=30,
        )]

    def normalize_validation(self, output_paths):
        return []


def _run(tmp_path, b_spec):
    """Job b depends on job a, which builds `shell.glb`."""
    adapter = _Adapter()
    adapter.seen = {}
    sched = Scheduler(
        index=Index(tmp_path / "index.sqlite"), cache=ContentCache(tmp_path / "cache"),
        registry=AdapterRegistry({adapter.adapter_id: adapter}),
        jobs_dir=tmp_path / "jobs",
        installation={"repositories": {adapter.adapter_id: str(tmp_path)},
                      "python_executable": sys.executable},
    )
    graph = JobGraph()
    graph.add(Job(job_id="m.a", mission_id="m", stage_id="a",
                  adapter_id=adapter.adapter_id))
    graph.add(Job(job_id="m.b", mission_id="m", stage_id="b",
                  adapter_id=adapter.adapter_id, depends_on=["m.a"]))
    summary = sched.run(graph, job_specs={"m.a": {"name": "a"}, "m.b": b_spec},
                        mission_id="m")
    return summary, adapter


# ---------------------------------------------------------------------------
# the scheduler half
# ---------------------------------------------------------------------------
def test_prepare_runs_at_dispatch_after_its_dependency_and_its_spec_is_the_one_used(tmp_path):
    """FAILS BEFORE 0.144.2: nothing ran `prepare`, so job b ran on the spec
    as planned -- which for Lot was a site sized before its building existed."""
    built = tmp_path / "jobs" / "m.a" / "1" / "out" / "shell.glb"
    calls = []

    def prepare(spec):
        calls.append(built.exists())
        return {**{k: v for k, v in spec.items() if k != "prepare"}, "measured": True}

    summary, adapter = _run(tmp_path, {"name": "b", "prepare": prepare})
    assert summary.succeeded, [(o.job.job_id, o.job.status) for o in summary.outcomes]
    assert calls == [True], "once, and only after the job it depends on had built"
    assert adapter.seen["b"].get("measured") is True
    assert "prepare" not in adapter.seen["b"]


def test_a_prepare_that_raises_fails_its_job_and_not_the_run(tmp_path):
    def prepare(spec):
        raise RuntimeError("the shell was never built")

    summary, adapter = _run(tmp_path, {"name": "b", "prepare": prepare})
    by_id = {o.job.job_id: o for o in summary.outcomes}
    assert by_id["m.a"].job.status == states.SUCCEEDED
    assert by_id["m.b"].job.status == states.FAILED
    assert "b" not in adapter.seen, "the tool never ran on an unfinished spec"


# ---------------------------------------------------------------------------
# the Lot half
# ---------------------------------------------------------------------------
def test_the_site_spec_is_written_again_from_the_same_arguments(tmp_path, monkeypatch):
    from apps.cli import commands
    calls = []

    def fake_write(ws, model, deli_out, **kw):
        calls.append((ws, model, deli_out, kw))
        return tmp_path / "site.json"

    monkeypatch.setattr(commands, "_write_site_spec", fake_write)
    spec = {"site_spec_path": str(tmp_path / "site.json"), "walkable": True,
            "skins_dir": "batch-merged", "prepare": object()}
    out = commands._site_spec_at_dispatch("ws", "model", "deli", spec,
                                          seed=9208, themed_scene=None)
    # everything the scheduler handed in, a batch's merged keys included,
    # and no prepare
    assert out == {"site_spec_path": str(tmp_path / "site.json"),
                   "walkable": True, "skins_dir": "batch-merged"}
    assert calls == [("ws", "model", "deli", {"seed": 9208, "themed_scene": None})]


def test_a_site_spec_that_would_land_somewhere_else_refuses(tmp_path, monkeypatch):
    from apps.cli import commands
    monkeypatch.setattr(commands, "_write_site_spec",
                        lambda *a, **k: tmp_path / "elsewhere.json")
    with pytest.raises(RuntimeError, match="moved between plan and dispatch"):
        commands._site_spec_at_dispatch(
            "ws", "model", "deli", {"site_spec_path": str(tmp_path / "site.json")},
            seed=1)


def test_the_plan_attaches_it_to_every_lot_job_that_writes_a_site_spec():
    from apps.cli import commands
    src = inspect.getsource(commands._job_specs_for_plan)
    lot = src[src.index('elif job.adapter_id == "lot":'):
              src.index('elif job.adapter_id == "walktest":')]
    assert "_write_site_spec(" in lot
    assert '"prepare"' in lot and "_site_spec_at_dispatch" in lot
'''

EDITS = {
    LF / "packages/jobs/scheduler.py": [(SCHED_OLD, SCHED_NEW)],
    LF / "apps/cli/commands/__init__.py": [(HELPER_ANCHOR, HELPER_NEW), (LOT_OLD, LOT_NEW)],
}
NEW_FILES = {LF / "tests/unit/test_site_spec_at_dispatch.py": TEST}


def main(root=None):
    """`root` points the patch at a copy of level_factory instead (the
    pre-flight copy, while a cold run is in flight)."""
    base = pathlib.Path(root) if root else LF
    staged = {}
    for path, pairs in EDITS.items():
        path = base / path.relative_to(LF)
        data = path.read_bytes()
        crlf = data.count(b"\r\n")
        assert crlf in (0, data.count(b"\n")), f"{path}: mixed line endings"
        eol = "\r\n" if crlf else "\n"
        text = data.decode("utf-8")
        for old, new in pairs:
            old, new = old.replace("\n", eol), new.replace("\n", eol)
            n = text.count(old)
            assert n == 1, f"{path}: anchor matched {n} times: {old[:70]!r}"
            text = text.replace(old, new)
        staged[path] = text
    for path, text in NEW_FILES.items():
        path = base / path.relative_to(LF)
        assert not path.exists(), f"{path} already exists"
        staged[path] = text
    for path, text in staged.items():
        path.write_bytes(text.encode("utf-8"))
        print("patched", path)


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else None)
