# Commit the walkable-pack pass: the step-up fix, the site packager's host
# project and engine check, the asset-path bug that made every pack unloadable,
# and gdcheck's invocation.
#
# Dry run by default. Add -Commit to commit. Nothing is pushed either way.
# Messages are plain per CLAUDE.md -- no trailers, no footers, no assistant
# references. -Branch is opt-in: these repos commit straight to main.
param([switch]$Commit, [string]$Branch = "")

$root = "C:\Projects\gabagool_studios\gabagool_factory"

# dist/ is build output: a pack folder plus its zip and sha256, regenerated by
# one command from inputs that ARE tracked. Committing it would put a second copy
# of every building .glb in the history.
$ignoreLot = @("dist/", "*.pre_step", "*.pre_walkable", "*.pre_paths",
               "*.pre_manifest")
$ignoreRoot = @("*.pre_invoke", "*.pre_step")

$msgLot = @'
lot_player: the step-up climbed tall obstacles and failed on curbs

    if absf(col.get_normal().y) < 0.2 and into.dot(-col.get_normal()) > 0.3:

A capsule does not meet a low step on a flat face. Contact lands on the bottom
hemisphere, so the normal is sloped, and the LOWER the step the more vertical it
gets: n.y = (R - h) / R. Requiring n.y < 0.2 requires h > 0.8 * R -- 0.28 m for
the 0.35 m body -- so nothing shorter ever set `blocked` and nothing shorter was
ever stepped. Between the tallest step a capsule walks up unassisted (0.1025 m)
and 0.28 m the body simply stopped. SIDEWALK_H is 0.16 and sat in the middle of
that band, which is why walking from a spawn toward the street stopped dead
despite a controller that nominally climbs 0.45 m.

Gate on cos(floor_max_angle) instead -- the same threshold the engine uses to
decide whether a contact counts as floor at all. n.y < cos(45 deg) means
h > 0.2929 * R = 0.1025 m, which is clearances.unassisted_step_max_m to four
decimals. Walking covers 0 to 0.1025, step-up covers 0.1025 to max_step_height,
no gap and no overlap, and the two bounds keep meeting if the body changes.
Confirmed by walking a pack: a kerb that stopped the body is now unremarkable.

The head-clearance probe ran to a hardcoded 1.7 m, clearing 1.65 m against a
1.8 m body, so it could lift the body into geometry its own head occupies. It
uses the body height now. Both that and max_step_height are set by the walk scene
from the contract, along with the collision offset and eye height -- the export
default said 0.45 while the contract said 0.5, three opinions about one body.

tests: test_step_thresholds pins the identity the fix rests on, for six radii and
four floor angles, plus the dead band the old constant created and the surface
heights Lot emits. It reads the shipped .gd, because arithmetic is worth nothing
if the code does not use it.

package: a site pack has never loaded in Godot

    ERROR: Resource file not found: res://buildings/warehouse_a02.glb
    PACK LOADS IN GODOT = False

write_godot_scene(portable=True) emits asset paths RELATIVE to the scene -- that
relativity is what lets the folder sit at any path in a consumer's project. The
packager then copied with os.path.basename(src), flattening
"buildings/warehouse_a02.glb" to "warehouse_a02.glb", one directory above where
the scene looks. In the walk scene it showed as three holes in the ground you
fall through: the ground is cut out under each building because buildings supply
their own floors, the buildings fail to load, the holes remain.

This was true of every site pack ever produced. It survived because a pack was
judged by its manifest, its deterministic zip and its sha256 -- three things
perfectly happy to describe a pack that cannot load. The sibling packager
(deli_counter/portable_building.py) has run a headless engine check since it was
written; this one never did, so nothing had ever asked Godot to open a pack.

So: --check <godot> imports the pack and loads its walk scene headless, failing
on a Godot error. And --walkable writes a host project.godot with the walk scene
as main scene, opt-in because the pack's contract is to nest inside someone
else's project and a nested project file breaks that. Both mirror the building
packager. Neither changes default output, so the deterministic zip is unaffected.

The host project also sets navigation/3d/default_cell_size and _cell_height from
the contract. The engine warned that a mesh baked at 0.10/0.15 was handed to a
navigation map defaulting to 0.25/0.25, which "can cause rasterization errors
with navigation mesh edges" -- edges in the wrong place, the defect class this
whole pass has been about. PACK_README tells a consumer to set them too, since a
dropped-in folder cannot set project settings for you.

The manifest walks the pack rather than listing it. os.listdir returns names, and
every name was a file only because the pack was flat; nesting the assets made
open(directory, "rb") a PermissionError. Recording relative paths also makes the
manifest describe the pack as the scene addresses it and agree with the zip,
which always stored nested paths.
'@

$msgRoot = @'
gdcheck: invoke the parser module, not a console script on PATH

`pip install gdtoolkit` succeeded and gdcheck still died with
FileNotFoundError [WinError 2], because it ran subprocess.run(["gdparse", path])
and pip had said in the same output that the Scripts directory it installed
gdparse.exe into was not on PATH. Depending on a console shim means depending on
a PATH entry the installer itself warns it did not make -- and CLAUDE.md tells
the reader to run this before any .gd leaves the machine, so the instruction was
unfollowable on a clean install.

Going through [sys.executable, "-m", "gdtoolkit.parser"] makes PATH irrelevant
and guarantees the parser comes from the same interpreter as the script.

The parser is probed once, before any file, rather than inferred from a failed
parse. A first attempt keyed on "No module named" appearing in stderr, and a
parser broken any other way does not say that -- it reported its own breakage as
a defect in the file being checked. A missing parser now prints what is wrong and
how to install it, the hand-written trap lint still runs, and the summary line
says NOT PARSED rather than claiming the file is clean.

Exit codes: 0 checked and clean, 1 checked and found problems, 2 could not fully
check. Same three-way distinction as check_steps.py and check_freshness.py, for
the same reason -- a check that could not run must not report what a clean run
reports.
'@

$repos = @(
  @{ Path = "$root\lot"; Msg = $msgLot;  Label = "lot";          Ignore = $ignoreLot },
  @{ Path = $root;       Msg = $msgRoot; Label = "factory root"; Ignore = $ignoreRoot }
)

foreach ($r in $repos) {
  Write-Host ""
  Write-Host "=========== $($r.Label) ===========" -ForegroundColor Cyan
  Push-Location $r.Path
  Write-Host "  branch: $((git rev-parse --abbrev-ref HEAD).Trim())"
  $status = git status --short
  if (-not $status) { Write-Host "  clean, nothing to commit"; Pop-Location; continue }
  $status | ForEach-Object { Write-Host "  $_" }

  if ($Commit) {
    if ($Branch) {
      # No 2>$null. Swallowing git's stderr is how a "branching to ..." line got
      # printed while the checkout failed and the commit landed on main anyway.
      Write-Host "  branching to $Branch"
      git checkout -b $Branch
      if ($LASTEXITCODE -ne 0) {
        git checkout $Branch
        if ($LASTEXITCODE -ne 0) {
          Write-Host "  could not switch to $Branch -- NOT committing" -ForegroundColor Red
          Pop-Location; continue
        }
      }
    }
    $gi = Join-Path $r.Path ".gitignore"
    $existing = if (Test-Path $gi) { Get-Content $gi } else { @() }
    $added = @($r.Ignore | Where-Object { $existing -notcontains $_ })
    if ($added) {
      Add-Content -Path $gi -Value ""
      Add-Content -Path $gi -Value "# build output and editor backups -- regenerable, not history"
      $added | ForEach-Object { Add-Content -Path $gi -Value $_ }
      Write-Host "  .gitignore += $($added -join ', ')"
    }
    git add -A
    # -F avoids PowerShell re-parsing a message that contains quotes and $null
    $tmp = [System.IO.Path]::GetTempFileName()
    Set-Content -Path $tmp -Value $r.Msg -Encoding UTF8
    git commit -F $tmp
    Remove-Item $tmp -Force
  }
  Pop-Location
}

Write-Host ""
if (-not $Commit) {
  Write-Host "Dry run. Nothing committed. Re-run with -Commit when the status above looks right." -ForegroundColor Yellow
} else {
  Write-Host "Committed. Nothing pushed." -ForegroundColor Green
}
